### ISSUE TITLE
代码有问题，执行报错

### ISSUE THREAD

**Issue by hl668** [Sheldonsix/A-python-script-of-AutoRclone-or-gclone#1]
你好，在Centos代码执行会报错。不会python，请问是哪里问题
[root@centos AutoRclone]# python 提取文件名邮箱.py 
Traceback (most recent call last):
  File "提取文件名邮箱.py", line 15, in <module>
    for filename in os.listdir() :
TypeError: listdir() takes exactly 1 argument (0 given)

文件路径我是这样写的：

#定义目录：目录下有多个文件需要处理，为 accounts 目录的路径，例如： path = 'D://AutoRclone//accounts'
path = '//root//AutoRclone//accounts'
#定义输出文件，路径可自定义，例如 fout = open("D://AutoRclone//accounts//res.txt", 'w')
fout = open("res.txt", 'w')

**Comment by Sheldonsix** [comment]
请用 python3 来运行该脚本
